{% set name = "pypdfium2" %}
{% set version = "4.30.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypdfium2-{{ version }}.tar.gz
  sha256: 5f5c7c6d03598e107d974f66b220a49436aceb191da34cda5f692be098a814ce

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - packaging
    - wheel !=0.38.0,!=0.38.1
    - ctypesgen-pypdfium2-team
    - pip
  run:
    - python

test:
  imports:
    - pypdfium2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypdfium2-team/pypdfium2
  summary: Python bindings to PDFium
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
