context:
  name: pypdfium2
  version: 4.30.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/pypdfium2-${{ version }}.tar.gz
  sha256: 48b5b7e5566665bc1015b9d69c1ebabe21f6aee468b509531c3c8318eeee2e16

build:
  number: 2
  skip: win
  script:
    content: python -m pip install . -vv --no-deps --no-build-isolation
    env:
      LDFLAGS: "-headerpad_max_install_names ${LDFLAGS}"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - packaging
    - wheel !=0.38.0,!=0.38.1
    - ctypesgen-pypdfium2-team
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - pypdfium2
      pip_check: true

about:
  summary: Python bindings to PDFium
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/pypdfium2-team/pypdfium2

extra:
  recipe-maintainers:
    - jan-janssen
